version: "3.8"

services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecomhub_network

  gateway-api:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "5500:5500"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    networks:
      - ecomhub_network

volumes:
  postgres_data:

networks:
  ecomhub_network:
    name: ecomhub_services_network