version: "3.8"

services:
  gateway-api:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "5500:5500"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    networks:
      - ecomhub_network

volumes:
  postgres_data:

networks:
  ecomhub_network:
    name: ecomhub_services_network