server:
  port: 8002

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: teste
            uri: http://localhost:8001/
            predicates:
              - Path=/teste
            filters:
              - SetPath=/api-docs