server:
  port: 5500
  address: 0.0.0.0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    url: /merged-docs

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: crawler
            uri: http://crawler-api:8001
            predicates:
              - Path=/ehcrawler/**
            filters:
              - RewritePath=/ehcrawler/(?<segment>.*), /ehcrawler/${segment}

  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

documentation:
  services:
    - name: gateway-api
      url: http://localhost:5500/api-docs
    - name: crawler-api
      url: http://crawler-api:8001/api-docs

logging:
  level:
    root: info
    br.com.ecomhub.gateway: trace
    org.hibernate.sql: debug
    org.hibernate.type: trace
