server:
  port: 8000
  address: 0.0.0.0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    url: http://localhost:8000/merged-docs

spring:
  doc:
    services:
      - name: gateway-api
        url: http://gateway-api:8000/api-docs
      - name: crawler-api
        url: http://crawler-api:8001/api-docs
  cloud:
    gateway:
      mvc:
        routes:
          - id: crawler
            uri: http://crawler-api:8001
            predicates:
              - Path=/ehcrawler/**
            filters:
              - RewritePath=/ehcrawler/(?<segment>.*), /ehcrawler/${segment}

  docker:
    compose:
      enabled: false

documentation:
  services:
    - name: gateway-api
      url: http://localhost:8000/api-docs
    - name: crawler-api
      url: http://crawler-api:8001/api-docs